import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { storyblokInit, getStoryblokApi, apiPlugin } from '@storyblok/react/rsc'
import { StoryblokProvider } from './components/StoryBlokProvider'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const cachedFetch = (input: any, init?: any): Promise<Response> => {
  return fetch(input, {
    ...init,
    cache: process.env.NODE_ENV==='development'?"no-store":"force-cache",
  })
}
storyblokInit({
  accessToken: process.env.STORYBLOK_API_TOKEN,
  use: [apiPlugin],
  apiOptions: {
    fetch: cachedFetch,
  },
})
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <StoryblokProvider>
      <html lang='en'>
        <body className='{inter.className}'>
          <header>
            <nav>
              <Link href={'/'}>Home</Link>
              <Link href={'/tours'}>Tour</Link>
            </nav>
          </header>
          {children}
        </body>
      </html>
    </StoryblokProvider>
  )
}
