import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { storyblokInit, getStoryblokApi, apiPlugin } from "@storyblok/react/rsc";
import { StoryblokProvider } from "./components/StoryBlokProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
storyblokInit (
  {
    accessToken : process.env.STORYBLOK_API_TOKEN,
    use:[apiPlugin]
  }
)
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoryblokProvider>
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
    </StoryblokProvider>
  );
}
